version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"  #MQTT TCP
      - "9001:9001"  #WebSocket
    volumes:
      - /home/ubuntu/myapp/mqtt-chat/mosquitto/config:/mosquitto/config
      - /home/ubuntu/myapp/mqtt-chat/mosquitto/data:/mosquitto/data
      - /home/ubuntu/myapp/mqtt-chat/mosquitto/log:/mosquitto/log

