[connections.sakila]
dialect = "mysql"
host = "localhost"
port = 3306
database = "sakila"
username = "user"
password = "user1981"
[connections.weather]
dialect = "mysql"
host = "localhost"
port = 3306
database = "weather_db"
username = "user"
password = "user1981"
